# Generated by Django 4.2.1 on 2023-05-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informsalary',
            name='summ_check',
            field=models.DecimalField(decimal_places=10, max_digits=100),
        ),
    ]
