# Generated by Django 4.2.1 on 2023-06-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0004_informsalary_date_next_raise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeconfirmemail',
            name='flag_verify',
            field=models.BooleanField(default=False),
        ),
    ]
